package sgi.javaMacros.ui;

public enum ActionCommands {
	SCAN_FOR_NEW_EVENT
	, ADD_APPLICATION
	, FIX_ALIASES
	, SAVE_CONFIG
	, SAVE_VARIANT
	, LOAD_VARIANT
	, EXIT_APPLICATION
	, CREATE_NEW_MACRO
	, ERASE_MACRO
	, FIND_MACRO
	, SCAN_FOR_NEW_EVENT_IN_MACRO
	, LOOKFOR_BACKUP_DIRECTORY
	, SET_INTERFACE_LANGUAGE
	, SELECT_MODIFIER
	, PAYLOAD
	, ADD_DEVICE
}