package sgi.javaMacros.ui;

public enum ActionCommands {
	SCAN_FOR_NEW_EVENT
	//	, ADD_APPLICATION//
	// , EDIT_APPLICATION
	//, FIX_ALIASES//
	, SAVE//
	, SAVE_MACROS_SNAPSHOT//
	//, LOAD_VARIANT//
	, EXIT_APPLICATION//
	, CREATE_NEW_MACRO//
	, ERASE_MACRO//
	, FIND_MACRO//
	, LOOKFOR_BACKUP_DIRECTORY//
	//, SET_INTERFACE_LANGUAGE//
	// , SELECT_MODIFIER//
	, LOAD_MACROS//
	// , EDIT_DEVICE
	, OPEN_SETTINGS//
	, MANAGE_DEVICES//
, LOAD_FROM_HIDMACROS


}