package sgi.javaMacros.os.windows;

import java.util.TreeMap;

/*
 * 
typedef struct tagRID_DEVICE_INFO {
  DWORD cbSize;
  DWORD dwType;
  union {
    RID_DEVICE_INFO_MOUSE    mouse;
    RID_DEVICE_INFO_KEYBOARD keyboard;
    RID_DEVICE_INFO_HID      hid;
  };
} RID_DEVICE_INFO, *PRID_DEVICE_INFO, *LPRID_DEVICE_INFO;
 * 
 * */
public class HIDPages {

	public static class HIDPage extends TreeMap<Integer, String> {
		public String getPageDescription() {
			return pageDescription;
		}

		public int getPageNumber() {
			return pageNumber;
		}

		/**
		 * 
		 */
		private static final long serialVersionUID = 1L;
		private String pageDescription;
		private int pageNumber;

		public HIDPage(int pageNumber, String pageDescription) {
			super();
			this.pageDescription = pageDescription;
			this.pageNumber = pageNumber;
		}
	}

	public static final TreeMap<Integer, HIDPage> allPages = new TreeMap<>();

	static {
		HIDPage page;
		allPages.put(1, page = new HIDPage(1, "DeskTop"));
		page.put(0x00, "Undefined");
		page.put(0x01, "Pointer");
		page.put(0x02, "Mouse");
		page.put(0x03, "Reserved");
		page.put(0x04, "Joystick");
		page.put(0x05, "Game Pad");
		page.put(0x06, "Keyboard");
		page.put(0x07, "Keypad");
		page.put(0x08, "Multi-axis Controller");
		page.put(0x30, "X");
		page.put(0x31, "Y");
		page.put(0x32, "Z");
		page.put(0x33, "Rx");
		page.put(0x34, "Ry");
		page.put(0x35, "Rz");
		page.put(0x36, "Slider");
		page.put(0x37, "Dial");
		page.put(0x38, "Wheel");
		page.put(0x39, "Hat Switch");
		page.put(0x3A, "Counted Buffer");
		page.put(0x3B, "Byte Count");
		page.put(0x3C, "Motion Wakeup");
		page.put(0x40, "Vx");
		page.put(0x41, "Vy");
		page.put(0x42, "Vz");
		page.put(0x43, "Vbrx");
		page.put(0x44, "Vbry");
		page.put(0x45, "Vbrx");
		page.put(0x46, "Vno");
		page.put(0x80, "System Control");
		page.put(0x81, "System Power Down");
		page.put(0x82, "System Sleep");
		page.put(0x83, "System Wake Up");
		page.put(0x84, "System Context Menu");
		page.put(0x85, "System Main Menu");
		page.put(0x86, "System App Menu");
		page.put(0x87, "System Menu Help");
		page.put(0x88, "System Menu Exit");
		page.put(0x89, "System Menu Select");
		page.put(0x8A, "System Menu Right");
		page.put(0x8B, "System Menu Left");
		page.put(0x8C, "System Menu Up");
		page.put(0x8D, "System Menu Down");
		page.put(0x90, "D-pad Up");
		page.put(0x91, "D-pad Down");
		page.put(0x92, "D-pad Right");
		page.put(0x93, "D-pad Left");

		allPages.put(2, page = new HIDPage(2, "Simulation Controls"));
		page.put(0x00, "Undefined");
		page.put(0x01, "Flight Simulation Device");
		page.put(0x02, "Automobile Simulation Device");
		page.put(0x03, "Tank Simulation Device");
		page.put(0x04, "Spaceship Simulation Device");
		page.put(0x05, "Submarine Simulation Device");
		page.put(0x06, "Sailing Simulation Device");
		page.put(0x07, "Motorcycle Simulation Device");
		page.put(0x08, "Sports Simulation Device");
		page.put(0x09, "Airplane Simulation Device");
		page.put(0x0A, "Helicopter Simulation Device");
		page.put(0x0B, "Magic Carpet Simulation Device");
		page.put(0x0C, "Bicycle");
		page.put(0x20, "Flight Control Stick");
		page.put(0x21, "Flight Stick");
		page.put(0x22, "Cyclic Control");
		page.put(0x23, "Cyclic Trim");
		page.put(0x24, "Flight Yoke");
		page.put(0x25, "Track Control");
		page.put(0x26, "Driving Control");
		page.put(0xB0, "Aileron");
		page.put(0xB1, "Aileron Trim");
		page.put(0xB2, "Anti-Torque Control");
		page.put(0xB3, "Auto-pilot Enable");
		page.put(0xB4, "Chaff Release");
		page.put(0xB5, "Collective Control");
		page.put(0xB6, "Dive Brake");
		page.put(0xB7, "Electronic Counter Measures");
		page.put(0xB8, "Elevator");
		page.put(0xB9, "Elevator Trim");
		page.put(0xBA, "Rudder");
		page.put(0xBB, "Throttle");
		page.put(0xBC, "Flight Communication");
		page.put(0xBD, "Flare Release");
		page.put(0xBE, "Landing Gear");
		page.put(0xBF, "Toe Brake");
		page.put(0xC0, "Trigger");
		page.put(0xC1, "Weapons Arm");
		page.put(0xC2, "Weapons Select");
		page.put(0xC3, "Wing Flaps");
		page.put(0xC4, "Accelerator");
		page.put(0xC5, "Brake");
		page.put(0xC6, "Clutch");
		page.put(0xC7, "Shifter");
		page.put(0xC8, "Steering");
		page.put(0xC9, "Turret Direction");
		page.put(0xCA, "Barrel Elevation");
		page.put(0xCB, "Dive Plane");
		page.put(0xCC, "Ballast");
		page.put(0xCD, "Bicycle Crank");
		page.put(0xCE, "Handle Bars");
		page.put(0xCF, "Front Brake");
		page.put(0xD0, "Rear Brake");
		allPages.put(3, page = new HIDPage(3, "VR Controls"));
		page.put(0x00, "Unidentified");
		page.put(0x01, "Belt");
		page.put(0x02, "Body Suit");
		page.put(0x03, "Flexor");
		page.put(0x04, "Glove");
		page.put(0x05, "Head Tracker");
		page.put(0x06, "Head Mounted Display");
		page.put(0x07, "Hand Tracker");
		page.put(0x08, "Oculometer");
		page.put(0x09, "Vest");
		page.put(0x0A, "Animatronic Device");
		page.put(0x20, "Stereo Enable");
		page.put(0x21, "Display Enable");
		allPages.put(4, page = new HIDPage(4, "Sports Controls"));
		page.put(0x00, "Unidentified");
		page.put(0x01, "Baseball Bat");
		page.put(0x02, "Golf Club");
		page.put(0x03, "Rowing Machine");
		page.put(0x04, "Treadmill");
		page.put(0x30, "Oar");
		page.put(0x31, "Slope");
		page.put(0x32, "Rate");
		page.put(0x33, "Stick Speed");
		page.put(0x34, "Stick Face Angle");
		page.put(0x35, "Stick Heel/Toe");
		page.put(0x36, "Stick Follow Through");
		page.put(0x37, "Stick Tempo");
		page.put(0x38, "Stick Type");
		page.put(0x39, "Stick Height");
		page.put(0x50, "Putter");
		page.put(0x51, "1 Iron");
		page.put(0x52, "2 Iron");
		page.put(0x53, "3 Iron");
		page.put(0x54, "4 Iron");
		page.put(0x55, "5 Iron");
		page.put(0x56, "6 Iron");
		page.put(0x57, "7 Iron");
		page.put(0x58, "8 Iron");
		page.put(0x59, "9 Iron");
		page.put(0x5A, "10 Iron");
		page.put(0x5B, "11 Iron");
		page.put(0x5C, "Sand Wedge");
		page.put(0x5D, "Loft Wedge");
		page.put(0x5E, "Power Wedge");
		page.put(0x5F, "1 Wood");
		page.put(0x60, "3 Wood");
		page.put(0x61, "5 Wood");
		page.put(0x62, "7 Wood");
		page.put(0x63, "9 Wood");
		allPages.put(5, page = new HIDPage(5, "Game Controls"));
		page.put(0x00, "Undefined");
		page.put(0x01, "3D Game Controller");
		page.put(0x02, "Pinball Device");
		page.put(0x03, "Gun Device");
		page.put(0x20, "Point of View");
		page.put(0x21, "Turn Right/Left");
		page.put(0x22, "Pitch Right/Left");
		page.put(0x23, "Roll Forward/Backward");
		page.put(0x24, "Move Right/Left");
		page.put(0x25, "Move Forward/Backward");
		page.put(0x26, "Move Up/Down");
		page.put(0x27, "Lean Right/Left");
		page.put(0x28, "Lean Forward/Backward");
		page.put(0x29, "Height of POV");
		page.put(0x2A, "Flipper");
		page.put(0x2B, "Secondary Flipper");
		page.put(0x2C, "Bump");
		page.put(0x2D, "New Game");
		page.put(0x2E, "Shoot Ball");
		page.put(0x2F, "Player");
		page.put(0x30, "Gun Bolt");
		page.put(0x31, "Gun Clip");
		page.put(0x32, "Gun Selector");
		page.put(0x33, "Gun Single Shot");
		page.put(0x34, "Gun Burst");
		page.put(0x35, "Gun Automatic");
		page.put(0x36, "Gun Safety");
		page.put(0x37, "Gamepad Fire/Jump");
		page.put(0x39, "Gamepad Trigger");
		allPages.put(7, page = new HIDPage(7, "Keyboard"));
		page.put(0x00, "Reserved (no event indicated)");
		page.put(0x01, "Keyboard ErrorRollOver");
		page.put(0x02, "Keyboard POSTFail");
		page.put(0x03, "Keyboard ErrorUndefined");
		page.put(0x04, "Keyboard a and A");
		page.put(0x05, "Keyboard b and B");
		page.put(0x06, "Keyboard c and C");
		page.put(0x07, "Keyboard d and D");
		page.put(0x08, "Keyboard e and E");
		page.put(0x09, "Keyboard f and F");
		page.put(0x0A, "Keyboard g and G");
		page.put(0x0B, "Keyboard h and H");
		page.put(0x0C, "Keyboard i and I");
		page.put(0x0D, "Keyboard j and J");
		page.put(0x0E, "Keyboard k and K");
		page.put(0x0F, "Keyboard l and L");
		page.put(0x10, "Keyboard m and M");
		page.put(0x11, "Keyboard n and N");
		page.put(0x12, "Keyboard o and O");
		page.put(0x13, "Keyboard p and P");
		page.put(0x14, "Keyboard q and Q");
		page.put(0x15, "Keyboard r and R");
		page.put(0x16, "Keyboard s and S");
		page.put(0x17, "Keyboard t and T");
		page.put(0x18, "Keyboard u and U");
		page.put(0x19, "Keyboard v and V");
		page.put(0x1A, "Keyboard w and W");
		page.put(0x1B, "Keyboard x and X");
		page.put(0x1C, "Keyboard y and Y");
		page.put(0x1D, "Keyboard z and Z");
		page.put(0x1E, "Keyboard 1 and !");
		page.put(0x1F, "Keyboard 2 and @");
		page.put(0x20, "Keyboard 3 and #");
		page.put(0x21, "Keyboard 4 and $");
		page.put(0x22, "Keyboard 5 and %");
		page.put(0x23, "Keyboard 6 and ^");
		page.put(0x24, "Keyboard 7 and &");
		page.put(0x25, "Keyboard 8 and *");
		page.put(0x26, "Keyboard 9 and (");
		page.put(0x27, "Keyboard 0 and )");
		page.put(0x28, "Keyboard Return (ENTER)");
		page.put(0x29, "Keyboard ESCAPE");
		page.put(0x2A, "Keyboard DELETE (Backspace)");
		page.put(0x2B, "Keyboard Tab");
		page.put(0x2C, "Keyboard Spacebar");
		page.put(0x2D, "Keyboard - and (underscore)");
		page.put(0x2E, "Keyboard = and +");
		page.put(0x2F, "Keyboard [ and {");
		page.put(0x30, "Keyboard ] and }");
		page.put(0x31, "Keyboard \\ and |");
		page.put(0x32, "Keyboard Non-US # and ~");
		page.put(0x33, "Keyboard ; and :");
		page.put(0x34, "Keyboard ' and \"");
		page.put(0x35, "Keyboard Grave Accent and Tilde");
		page.put(0x36, "Keyboard, and <");
		page.put(0x37, "Keyboard . and >");
		page.put(0x38, "Keyboard / and ?");
		page.put(0x39, "Keyboard Caps Lock");
		page.put(0x3A, "Keyboard F1");
		page.put(0x3B, "Keyboard F2");
		page.put(0x3C, "Keyboard F3");
		page.put(0x3D, "Keyboard F4");
		page.put(0x3E, "Keyboard F5");
		page.put(0x3F, "Keyboard F6");
		page.put(0x40, "Keyboard F7");
		page.put(0x41, "Keyboard F8");
		page.put(0x42, "Keyboard F9");
		page.put(0x43, "Keyboard F10");
		page.put(0x44, "Keyboard F11");
		page.put(0x45, "Keyboard F12");
		page.put(0x46, "Keyboard PrintScreen");
		page.put(0x47, "Keyboard Scroll Lock");
		page.put(0x48, "Keyboard Pause");
		page.put(0x49, "Keyboard Insert");
		page.put(0x4A, "Keyboard Home");
		page.put(0x4B, "Keyboard PageUp");
		page.put(0x4C, "Keyboard Delete Forward");
		page.put(0x4D, "Keyboard End");
		page.put(0x4E, "Keyboard PageDown");
		page.put(0x4F, "Keyboard RightArrow");
		page.put(0x50, "Keyboard LeftArrow");
		page.put(0x51, "Keyboard DownArrow");
		page.put(0x52, "Keyboard UpArrow");
		page.put(0x53, "Keypad Num Lock and Clear");
		page.put(0x54, "Keypad /");
		page.put(0x55, "Keypad *");
		page.put(0x56, "Keypad -");
		page.put(0x57, "Keypad +");
		page.put(0x58, "Keypad ENTER");
		page.put(0x59, "Keypad 1 and End");
		page.put(0x5A, "Keypad 2 and Down Arrow");
		page.put(0x5B, "Keypad 3 and PageDn");
		page.put(0x5C, "Keypad 4 and Left Arrow");
		page.put(0x5D, "Keypad 5");
		page.put(0x5E, "Keypad 6 and Right Arrow");
		page.put(0x5F, "Keypad 7 and Home");
		page.put(0x60, "Keypad 8 and Up Arrow");
		page.put(0x61, "Keypad 9 and PageUp");
		page.put(0x62, "Keypad 0 and Insert");
		page.put(0x63, "Keypad . and Delete");
		page.put(0x64, "Keyboard Non-US \\ and |");
		page.put(0x65, "Keyboard Application");
		page.put(0x66, "Keyboard Power");
		page.put(0x67, "Keypad =");
		page.put(0x68, "Keyboard F13");
		page.put(0x69, "Keyboard F14");
		page.put(0x6A, "Keyboard F15");
		page.put(0x6B, "Keyboard F16");
		page.put(0x6C, "Keyboard F17");
		page.put(0x6D, "Keyboard F18");
		page.put(0x6E, "Keyboard F19");
		page.put(0x6F, "Keyboard F20");
		page.put(0x70, "Keyboard F21");
		page.put(0x71, "Keyboard F22");
		page.put(0x72, "Keyboard F23");
		page.put(0x73, "Keyboard F24");
		page.put(0x74, "Keyboard Execute");
		page.put(0x75, "Keyboard Help");
		page.put(0x76, "Keyboard Menu");
		page.put(0x77, "Keyboard Select");
		page.put(0x78, "Keyboard Stop");
		page.put(0x79, "Keyboard Again");
		page.put(0x7A, "Keyboard Undo");
		page.put(0x7B, "Keyboard Cut");
		page.put(0x7C, "Keyboard Copy");
		page.put(0x7D, "Keyboard Paste");
		page.put(0x7E, "Keyboard Find");
		page.put(0x7F, "Keyboard Mute");
		page.put(0x80, "Keyboard Volume Up");
		page.put(0x81, "Keyboard Volume Down");
		page.put(0x82, "Keyboard Locking Caps Lock");
		page.put(0x83, "Keyboard Locking Num Lock");
		page.put(0x84, "Keyboard Locking Scroll Lock");
		page.put(0x85, "Keypad Comma");
		page.put(0x86, "Keypad Equal Sign");
		page.put(0x87, "Keyboard International1");
		page.put(0x88, "Keyboard International2");
		page.put(0x89, "Keyboard International3");
		page.put(0x8A, "Keyboard International4");
		page.put(0x8B, "Keyboard International5");
		page.put(0x8C, "Keyboard International6");
		page.put(0x8D, "Keyboard International7");
		page.put(0x8E, "Keyboard International8");
		page.put(0x8F, "Keyboard International9");
		page.put(0x90, "Keyboard LANG1");
		page.put(0x91, "Keyboard LANG2");
		page.put(0x92, "Keyboard LANG3");
		page.put(0x93, "Keyboard LANG4");
		page.put(0x94, "Keyboard LANG5");
		page.put(0x95, "Keyboard LANG6");
		page.put(0x96, "Keyboard LANG7");
		page.put(0x97, "Keyboard LANG8");
		page.put(0x98, "Keyboard LANG9");
		page.put(0x99, "Keyboard Alternate Erase");
		page.put(0x9A, "Keyboard SysReq/Attention");
		page.put(0x9B, "Keyboard Cancel");
		page.put(0x9C, "Keyboard Clear");
		page.put(0x9D, "Keyboard Prior");
		page.put(0x9E, "Keyboard Return");
		page.put(0x9F, "Keyboard Separator");
		page.put(0xA0, "Keyboard Out");
		page.put(0xA1, "Keyboard Oper");
		page.put(0xA2, "Keyboard Clear/Again");
		page.put(0xA3, "Keyboard CrSel/Props");
		page.put(0xA4, "Keyboard ExSel");
		page.put(0xE0, "Keyboard LeftControl");
		page.put(0xE1, "Keyboard LeftShift");
		page.put(0xE2, "Keyboard LeftAlt");
		page.put(0xE3, "Keyboard Left GUI");
		page.put(0xE4, "Keyboard RightControl");
		page.put(0xE5, "Keyboard RightShift");
		page.put(0xE6, "Keyboard RightAlt");
		page.put(0xE7, "Keyboard Right GUI");
		allPages.put(8, page = new HIDPage(8, "LEDs"));
		page.put(0x00, "Undefined");
		page.put(0x01, "Num Lock");
		page.put(0x02, "Caps Lock");
		page.put(0x03, "Scroll Lock");
		page.put(0x04, "Compose");
		page.put(0x05, "Kana");
		page.put(0x06, "Power");
		page.put(0x07, "Shift");
		page.put(0x08, "Do Not Disturb");
		page.put(0x09, "Mute");
		page.put(0x0A, "Tone Enable");
		page.put(0x0B, "High Cut Filter");
		page.put(0x0C, "Low Cut Filter");
		page.put(0x0D, "Equalizer Enable");
		page.put(0x0E, "Sound Field On");
		page.put(0x0F, "Surround Field On");
		page.put(0x10, "Repeat");
		page.put(0x11, "Stereo");
		page.put(0x12, "Sampling Rate Detect");
		page.put(0x13, "Spinning");
		page.put(0x14, "CAV");
		page.put(0x15, "CLV");
		page.put(0x16, "Recording Format Detect");
		page.put(0x17, "Off-Hook");
		page.put(0x18, "Ring");
		page.put(0x19, "Message Waiting");
		page.put(0x1A, "Data Mode");
		page.put(0x1B, "Battery Operation");
		page.put(0x1C, "Battery OK");
		page.put(0x1D, "Battery Low");
		page.put(0x1E, "Speaker");
		page.put(0x1F, "Head Set");
		page.put(0x20, "Hold");
		page.put(0x21, "Microphone");
		page.put(0x22, "Coverage");
		page.put(0x23, "Night Mode");
		page.put(0x24, "Send Calls");
		page.put(0x25, "Call Pickup");
		page.put(0x26, "Conference");
		page.put(0x27, "Stand-by");
		page.put(0x28, "Camera On");
		page.put(0x29, "Camera Off");
		page.put(0x2A, "On-Line");
		page.put(0x2B, "Off-Line");
		page.put(0x2C, "Busy");
		page.put(0x2D, "Ready");
		page.put(0x2E, "Paper-Out");
		page.put(0x2F, "Paper-Jam");
		page.put(0x30, "Remote");
		page.put(0x31, "Forward");
		page.put(0x32, "Reverse");
		page.put(0x33, "Stop");
		page.put(0x34, "Rewind");
		page.put(0x35, "Fast Forward");
		page.put(0x36, "Play");
		page.put(0x37, "Pause");
		page.put(0x38, "Record");
		page.put(0x39, "Error");
		page.put(0x3A, "Usage Selected Indicator");
		page.put(0x3B, "Usage In Use Indicator");
		page.put(0x3C, "Usage Multi Mode Indicator");
		page.put(0x3D, "Indicator On");
		page.put(0x3E, "Indicator Flash");
		page.put(0x3F, "Indicator Slow Blink");
		page.put(0x40, "Indicator Fast Blink");
		page.put(0x41, "Indicator Off");
		page.put(0x42, "Flash On Time");
		page.put(0x43, "Slow Blink On Time");
		page.put(0x44, "Slow Blink Off Time");
		page.put(0x45, "Fast Blink On Time");
		page.put(0x46, "Fast Blink Off Time");
		page.put(0x47, "Usage Indicator Color");
		page.put(0x48, "Red");
		page.put(0x49, "Green");
		page.put(0x4A, "Amber");
		page.put(0x4B, "Generic Indicator");
		page.put(0x4C, "System Suspend");
		page.put(0x4D, "External Power Connected");
		page.put(0x4C, "-FFFF	Reserved");
		allPages.put(9, page = new HIDPage(9, "Button"));
		page.put(0x00, "No Button Pressed");
		for (int i = 1; i < 256; i++) {
			page.put(i, "Button " + i);
		}

		allPages.put(10, page = new HIDPage(10, "Ordinal"));
		page.put(0x00, "Unused");
		for (int i = 1; i < 256; i++) {
			page.put(i, "Instance " + i);
		}

		allPages.put(11, page = new HIDPage(11, "Telephony"));
		page.put(0x00, "Unassigned");
		page.put(0x01, "Phone");
		page.put(0x02, "Answering Machine");
		page.put(0x03, "Message Controls");
		page.put(0x04, "Handset");
		page.put(0x05, "Headset");
		page.put(0x06, "Telephony Key Pad");
		page.put(0x07, "Programmable Button");
		page.put(0x20, "Hook Switch");
		page.put(0x21, "Flash");
		page.put(0x22, "Feature");
		page.put(0x23, "Hold");
		page.put(0x24, "Redial");
		page.put(0x25, "Transfer");
		page.put(0x26, "Drop");
		page.put(0x27, "Park");
		page.put(0x28, "Forward Calls");
		page.put(0x29, "Alternate Function");
		page.put(0x2A, "Line");
		page.put(0x2B, "Speaker Phone");
		page.put(0x2C, "Conference");
		page.put(0x2D, "Ring Enable");
		page.put(0x2E, "Ring Select");
		page.put(0x2F, "Phone Mute");
		page.put(0x30, "Caller ID");
		page.put(0x50, "Speed Dial");
		page.put(0x51, "Store Number");
		page.put(0x52, "Recall Number");
		page.put(0x53, "Phone Directory");
		page.put(0x70, "Voice Mail");
		page.put(0x71, "Screen Calls");
		page.put(0x72, "Do Not Disturb");
		page.put(0x73, "Message");
		page.put(0x74, "Answer On/Off");
		page.put(0x90, "Inside Dial Tone");
		page.put(0x91, "Outside Dial Tone");
		page.put(0x92, "Inside Ring Tone");
		page.put(0x93, "Outside Ring Tone");
		page.put(0x94, "Priority Ring Tone");
		page.put(0x95, "Inside Ringback");
		page.put(0x96, "Priority Ringback");
		page.put(0x97, "Line Busy Tone");
		page.put(0x98, "Reorder Tone");
		page.put(0x99, "Call Waiting Tone");
		page.put(0x9A, "Confirmation Tone 1");
		page.put(0x9B, "Confirmation Tone 2");
		page.put(0x9C, "Tones Off");
		page.put(0xB0, "Phone Key 0");
		page.put(0xB1, "Phone Key 1");
		page.put(0xB2, "Phone Key 2");
		page.put(0xB3, "Phone Key 3");
		page.put(0xB4, "Phone Key 4");
		page.put(0xB5, "Phone Key 5");
		page.put(0xB6, "Phone Key 6");
		page.put(0xB7, "Phone Key 7");
		page.put(0xB8, "Phone Key 8");
		page.put(0xB9, "Phone Key 9");
		page.put(0xBA, "Phone Key Star");
		page.put(0xBB, "Phone Key Pound");
		page.put(0xBC, "Phone Key A");
		page.put(0xBD, "Phone Key B");
		page.put(0xBE, "Phone Key C");
		page.put(0xBF, "Phone Key D");
		allPages.put(12, page = new HIDPage(12, "Consumer"));
		page.put(0x00, "Unassigned");
		page.put(0x01, "Consumer Control");
		page.put(0x02, "Numeric Key Pad");
		page.put(0x03, "Programmable Buttons");
		page.put(0x20, "+10");
		page.put(0x21, "+100");
		page.put(0x22, "AM/PM");
		page.put(0x30, "Power");
		page.put(0x31, "Reset");
		page.put(0x32, "Sleep");
		page.put(0x33, "Sleep After");
		page.put(0x34, "Sleep Mode");
		page.put(0x35, "Illumination");
		page.put(0x36, "Function Buttons");
		page.put(0x40, "Menu");
		page.put(0x41, "Menu  Pick");
		page.put(0x42, "Menu Up");
		page.put(0x43, "Menu Down");
		page.put(0x44, "Menu Left");
		page.put(0x45, "Menu Right");
		page.put(0x46, "Menu Escape");
		page.put(0x47, "Menu Value Increase");
		page.put(0x48, "Menu Value Decrease");
		page.put(0x60, "Data On Screen");
		page.put(0x61, "Closed Caption");
		page.put(0x62, "Closed Caption Select");
		page.put(0x63, "VCR/TV");
		page.put(0x64, "Broadcast Mode");
		page.put(0x65, "Snapshot");
		page.put(0x66, "Still");
		page.put(0x80, "Selection");
		page.put(0x81, "Assign Selection");
		page.put(0x82, "Mode Step");
		page.put(0x83, "Recall Last");
		page.put(0x84, "Enter Channel");
		page.put(0x85, "Order Movie");
		page.put(0x86, "Channel");
		page.put(0x87, "Media Selection");
		page.put(0x88, "Media Select Computer");
		page.put(0x89, "Media Select TV");
		page.put(0x8A, "Media Select WWW");
		page.put(0x8B, "Media Select DVD");
		page.put(0x8C, "Media Select Telephone");
		page.put(0x8D, "Media Select Program Guide");
		page.put(0x8E, "Media Select Video Phone");
		page.put(0x8F, "Media Select Games");
		page.put(0x90, "Media Select Messages");
		page.put(0x91, "Media Select CD");
		page.put(0x92, "Media Select VCR");
		page.put(0x93, "Media Select Tuner");
		page.put(0x94, "Quit");
		page.put(0x95, "Help");
		page.put(0x96, "Media Select Tape");
		page.put(0x97, "Media Select Cable");
		page.put(0x98, "Media Select Satellite");
		page.put(0x99, "Media Select Security");
		page.put(0x9A, "Media Select Home");
		page.put(0x9B, "Media Select Call");
		page.put(0x9C, "Channel Increment");
		page.put(0x9D, "Channel Decrement");
		page.put(0x9E, "Media Select SAP");
		page.put(0xA0, "VCR Plus");
		page.put(0xA1, "Once");
		page.put(0xA2, "Daily");
		page.put(0xA3, "Weekly");
		page.put(0xA4, "Monthly");
		page.put(0xB0, "Play");
		page.put(0xB1, "Pause");
		page.put(0xB2, "Record");
		page.put(0xB3, "Fast Forward");
		page.put(0xB4, "Rewind");
		page.put(0xB5, "Scan Next Track");
		page.put(0xB6, "Scan Previous Track");
		page.put(0xB7, "Stop");
		page.put(0xB8, "Eject");
		page.put(0xB9, "Random Play");
		page.put(0xBA, "Select DisC");
		page.put(0xBB, "Enter Disc");
		page.put(0xBC, "Repeat");
		page.put(0xBD, "Tracking");
		page.put(0xBE, "Track Normal");
		page.put(0xBF, "Slow Tracking");
		page.put(0xC0, "Frame Forward");
		page.put(0xC1, "Frame Back");
		page.put(0xC2, "Mark");
		page.put(0xC3, "Clear Mark");
		page.put(0xC4, "Repeat From Mark");
		page.put(0xC5, "Return To Mark");
		page.put(0xC6, "Search Mark Forward");
		page.put(0xC7, "Search Mark Backwards");
		page.put(0xC8, "Counter Reset");
		page.put(0xC9, "Show Counter");
		page.put(0xCA, "Tracking Increment");
		page.put(0xCB, "Tracking Decrement");
		page.put(0xE0, "Volume");
		page.put(0xE1, "Balance");
		page.put(0xE2, "Mute");
		page.put(0xE3, "Bass");
		page.put(0xE4, "Treble");
		page.put(0xE5, "Bass Boost");
		page.put(0xE6, "Surround Mode");
		page.put(0xE7, "Loudness");
		page.put(0xE8, "MPX");
		page.put(0xE9, "Volume Up");
		page.put(0xEA, "Volume Down");
		page.put(0xF0, "Speed Select");
		page.put(0xF1, "Playback Speed");
		page.put(0xF2, "Standard Play");
		page.put(0xF3, "Long Play");
		page.put(0xF4, "Extended Play");
		page.put(0xF5, "Slow");
		page.put(0x100, "Fan Enable");
		page.put(0x101, "Fan Speed");
		page.put(0x102, "Light");
		page.put(0x103, "Light Illumination Level");
		page.put(0x104, "Climate Control Enable");
		page.put(0x105, "Room Temperature");
		page.put(0x106, "Security Enable");
		page.put(0x107, "Fire Alarm");
		page.put(0x108, "Police Alarm");
		page.put(0x150, "Balance Right");
		page.put(0x151, "Balance Left");
		page.put(0x152, "Bass Increment");
		page.put(0x153, "Bass Decrement");
		page.put(0x154, "Treble Increment");
		page.put(0x155, "Treble Decrement");
		page.put(0x160, "Speaker System");
		page.put(0x161, "Channel Left");
		page.put(0x162, "Channel Right");
		page.put(0x163, "Channel Center");
		page.put(0x164, "Channel Front");
		page.put(0x165, "Channel Center Front");
		page.put(0x166, "Channel Side");
		page.put(0x167, "Channel Surround");
		page.put(0x168, "Channel Low Frequency Enhancement");
		page.put(0x169, "Channel Top");
		page.put(0x16A, "Channel Unknown");
		page.put(0x170, "Sub-channel");
		page.put(0x171, "Sub-channel Increment");
		page.put(0x172, "Sub-channel Decrement");
		page.put(0x173, "Alternate Audio Increment");
		page.put(0x174, "Alternate Audio Decrement");
		page.put(0x180, "Application Launch Buttons");
		page.put(0x181, "AL Launch Button Configuration Tool");
		page.put(0x182, "AL Programmable Button Configuration");
		page.put(0x183, "AL Consumer Control Configuration");
		page.put(0x184, "AL Word Processor");
		page.put(0x185, "AL Text Editor");
		page.put(0x186, "AL Spreadsheet");
		page.put(0x187, "AL Graphics Editor");
		page.put(0x188, "AL Presentation App");
		page.put(0x189, "AL Database App");
		page.put(0x18A, "AL Email Reader");
		page.put(0x18B, "AL Newsreader");
		page.put(0x18C, "AL Voicemail");
		page.put(0x18D, "AL Contacts/Address Book");
		page.put(0x18E, "AL Calendar/Schedule");
		page.put(0x18F, "AL Task/Project Manager");
		page.put(0x190, "AL Log/Journal/Timecard");
		page.put(0x191, "AL Checkbook/Finance");
		page.put(0x192, "AL Calculator");
		page.put(0x193, "AL A/V Capture/Playback");
		page.put(0x194, "AL Local Machine Browser");
		page.put(0x195, "AL LAN/WAN Browser");
		page.put(0x196, "AL Internet Browser");
		page.put(0x197, "AL Remote Networking/ISP Connect");
		page.put(0x198, "AL Network Conference");
		page.put(0x199, "AL Network Chat");
		page.put(0x19A, "AL Telephony/Dialer");
		page.put(0x19B, "AL Logon");
		page.put(0x19C, "AL Logoff");
		page.put(0x19D, "AL Logon/Logoff");
		page.put(0x19E, "AL Terminal Lock/Screensaver");
		page.put(0x19F, "AL Control Panel");
		page.put(0x1A0, "AL Command Line Processor/Run");
		page.put(0x1A1, "AL Process/Task Manager");
		page.put(0x1A2, "AL Select Tast/Application");
		page.put(0x1A3, "AL Next Task/Application");
		page.put(0x1A4, "AL Previous Task/Application");
		page.put(0x1A5, "AL Preemptive Halt Task/Application");
		page.put(0x200, "Generic GUI Application Controls");
		page.put(0x201, "AC New");
		page.put(0x202, "AC Open");
		page.put(0x203, "AC Close");
		page.put(0x204, "AC Exit");
		page.put(0x205, "AC Maximize");
		page.put(0x206, "AC Minimize");
		page.put(0x207, "AC Save");
		page.put(0x208, "AC Print");
		page.put(0x209, "AC Properties");
		page.put(0x21A, "AC Undo");
		page.put(0x21B, "AC Copy");
		page.put(0x21C, "AC Cut");
		page.put(0x21D, "AC Paste");
		page.put(0x21E, "AC Select All");
		page.put(0x21F, "AC Find");
		page.put(0x220, "AC Find and Replace");
		page.put(0x221, "AC Search");
		page.put(0x222, "AC Go To");
		page.put(0x223, "AC Home");
		page.put(0x224, "AC Back");
		page.put(0x225, "AC Forward");
		page.put(0x226, "AC Stop");
		page.put(0x227, "AC Refresh");
		page.put(0x228, "AC Previous Link");
		page.put(0x229, "AC Next Link");
		page.put(0x22A, "AC Bookmarks");
		page.put(0x22B, "AC History");
		page.put(0x22C, "AC Subscriptions");
		page.put(0x22D, "AC Zoom In");
		page.put(0x22E, "AC Zoom Out");
		page.put(0x22F, "AC Zoom");
		page.put(0x230, "AC Full Screen View");
		page.put(0x231, "AC Normal View");
		page.put(0x232, "AC View Toggle");
		page.put(0x233, "AC Scroll Up");
		page.put(0x234, "AC Scroll Down");
		page.put(0x235, "AC Scroll");
		page.put(0x236, "AC Pan Left");
		page.put(0x237, "AC Pan Right");
		page.put(0x238, "AC Pan");
		page.put(0x239, "AC New Window");
		page.put(0x23A, "AC Tile Horizontally");
		page.put(0x23B, "AC Tile Vertically");
		page.put(0x23C, "AC Format");
		allPages.put(13, page = new HIDPage(13, "Digitizer"));
		page.put(0x00, "Undefined");
		page.put(0x01, "Digitizer");
		page.put(0x02, "Pen");
		page.put(0x03, "Light Pen");
		page.put(0x04, "Touch Screen");
		page.put(0x05, "Touch Pad");
		page.put(0x06, "White Board");
		page.put(0x07, "Coordinate Measuring Machine");
		page.put(0x08, "3-D Digitizer");
		page.put(0x09, "Stereo Plotter");
		page.put(0x0A, "Articulated Arm");
		page.put(0x0B, "Armature");
		page.put(0x0C, "Multiple Point Digitizer");
		page.put(0x0D, "Free Space Wand");
		page.put(0x20, "Stylus");
		page.put(0x21, "Puck");
		page.put(0x22, "Finger");
		page.put(0x30, "Tip Pressure");
		page.put(0x31, "Barrel Pressure");
		page.put(0x32, "In Range");
		page.put(0x33, "Touch");
		page.put(0x34, "Untouch");
		page.put(0x35, "Tap");
		page.put(0x36, "Quality");
		page.put(0x37, "Data Valid");
		page.put(0x38, "Transducer Index");
		page.put(0x39, "Tablet Function Keys");
		page.put(0x3A, "Program Change Keys");
		page.put(0x3B, "Battery Strength");
		page.put(0x3C, "Invert");
		page.put(0x3D, "X Tilt");
		page.put(0x3E, "Y Tilt");
		page.put(0x3F, "Azimuth");
		page.put(0x40, "Altitude");
		page.put(0x41, "Twist");
		page.put(0x42, "Tip Switch");
		page.put(0x43, "Secondary Tip Switch");
		page.put(0x44, "Barrel Switch");
		page.put(0x45, "Eraser");
		page.put(0x46, "Tablet Pick");
		allPages.put(15, page = new HIDPage(15, "Physical Interface Device"));
		allPages.put(16, page = new HIDPage(16, "Unicode"));
		// * Unicode Char u%04x
		allPages.put(20, page = new HIDPage(20, "Alphnumeric Display"));
		page.put(0x00, "Undefined");
		page.put(0x01, "Alphanumeric Display");
		page.put(0x20, "Display Attributes Report");
		page.put(0x21, "ASCII Character Set");
		page.put(0x22, "Data Read Back");
		page.put(0x23, "Font Read Back");
		page.put(0x24, "Display Control Report");
		page.put(0x25, "Clear Display");
		page.put(0x26, "Display Enable");
		page.put(0x27, "Screen Saver DelayAction");
		page.put(0x28, "Screen Saver Enable");
		page.put(0x29, "Vertical Scroll");
		page.put(0x2A, "Horizontal Scroll");
		page.put(0x2B, "Character Report");
		page.put(0x2C, "Display Data");
		page.put(0x2D, "Display Status");
		page.put(0x2E, "Stat Not Ready");
		page.put(0x2F, "Stat Ready");
		page.put(0x30, "Err Not a loadable character");
		page.put(0x31, "Err Font data cannot be read");
		page.put(0x32, "Cursor Position Report");
		page.put(0x33, "Row");
		page.put(0x34, "Column");
		page.put(0x35, "Rows");
		page.put(0x36, "Columns");
		page.put(0x37, "Cursor Pixel Positioning");
		page.put(0x38, "Cursor Mode");
		page.put(0x39, "Cursor Enable");
		page.put(0x3A, "Cursor Blink");
		page.put(0x3B, "Font Report");
		page.put(0x3C, "Font Data");
		page.put(0x3D, "Character Width");
		page.put(0x3E, "Character Height");
		page.put(0x3F, "Character Spacing Horizontal");
		page.put(0x40, "Character Spacing Vertical");
		page.put(0x41, "Unicode Character Set");

		allPages.put(128, page = new HIDPage(128, "Monitor"));
		page.put(0x00, "Undefined");
		page.put(0x01, "Monitor Control");
		page.put(0x02, "EDID Information");
		page.put(0x03, "VDIF Information");
		page.put(0x04, "VESA Version");
		page.put(0x05, "On Screen Display");
		page.put(0x06, "Auto Size Center");
		page.put(0x07, "Polarity Horz Synch");
		page.put(0x08, "Polarity Vert Synch");
		page.put(0x09, "Sync Type");
		page.put(0x0A, "Screen Position");
		page.put(0x0B, "Horizontal Frequency");
		page.put(0x0C, "Vertical Frequency");

		allPages.put(129, page = new HIDPage(129, "Monitor Enumerated Values"));
		page.put(0x00, "unassigned");

		allPages.put(130, page = new HIDPage(130, "VESA Virtual Controls"));
		page.put(0x10, "Brightness");
		page.put(0x12, "Contrast");
		page.put(0x16, "Video Gain Red");
		page.put(0x18, "Video Gain Green");
		page.put(0x1A, "Video Gain Blue");
		page.put(0x1C, "Focus");
		page.put(0x20, "Horizontal Position");
		page.put(0x22, "Horizontal Size");
		page.put(0x24, "Horizontal Pincushion");
		page.put(0x26, "Horizontal Pincushion Balance");
		page.put(0x28, "Horizontal Misconvergence");
		page.put(0x2A, "Horizontal Linearity");
		page.put(0x2C, "Horizontal Linearity Balance");
		page.put(0x30, "Vertical Position");
		page.put(0x32, "Vertical Size");
		page.put(0x34, "Vertical Pincushion");
		page.put(0x36, "Vertical Pincushion Balance");
		page.put(0x38, "Vertical Misconvergence");
		page.put(0x3A, "Vertical Linearity");
		page.put(0x3C, "Vertical Linearity Balance");
		page.put(0x40, "Parallelogram Distortion");
		page.put(0x42, "Trapezoidal Distortion");
		page.put(0x44, "Tilt");
		page.put(0x46, "Top Corner Distortion Control");
		page.put(0x48, "Top Corner Distortion Balance");
		page.put(0x4A, "Bottom Corner Distortion Control");
		page.put(0x4C, "Bottom Corner Distortion Balance");
		page.put(0x56, "Moire Horizontal");
		page.put(0x58, "Moire Vertical");
		page.put(0x5E, "Input Level Select");
		page.put(0x60, "Input Source Select");
		page.put(0x62, "Stereo Mode");
		page.put(0x6C, "Video Black Level Red");
		page.put(0x6E, "Video Black Level Green");
		page.put(0x70, "Video Black Level Blue");
		allPages.put(131, page = new HIDPage(131, "VESA Command"));
		page.put(0x00, "Undefined");
		page.put(0x01, "Settings");
		page.put(0x02, "Degauss");
		allPages.put(132, page = new HIDPage(132, "Power Device"));
		page.put(0x00, "Undefined");
		page.put(0x01, "iName");
		page.put(0x02, "PresentStatus");
		page.put(0x03, "ChangedStatus");
		page.put(0x04, "UPS");
		page.put(0x05, "PowerSupply");
		page.put(0x10, "BatterySystem");
		page.put(0x11, "BatterySystemID");
		page.put(0x12, "Battery");
		page.put(0x13, "BatteryID");
		page.put(0x14, "Charger");
		page.put(0x15, "ChargerID");
		page.put(0x16, "PowerConverter");
		page.put(0x17, "PowerConverterID");
		page.put(0x18, "OutletSystem");
		page.put(0x19, "OutletSystemID");
		page.put(0x1A, "Input");
		page.put(0x1B, "InputID");
		page.put(0x1C, "Output");
		page.put(0x1D, "OutputID");
		page.put(0x1E, "Flow");
		page.put(0x1F, "FlowID");
		page.put(0x20, "Outlet");
		page.put(0x21, "OutletID");
		page.put(0x22, "Gang");
		page.put(0x23, "GangID");
		page.put(0x24, "Sink");
		page.put(0x25, "SinkID");
		page.put(0x30, "Voltage");
		page.put(0x31, "Current");
		page.put(0x32, "Frequency");
		page.put(0x33, "ApparentPower");
		page.put(0x34, "ActivePower");
		page.put(0x35, "PercentLoad");
		page.put(0x36, "Temperature");
		page.put(0x37, "Humidity");
		page.put(0x40, "ConfigVoltage");
		page.put(0x41, "ConfigCurrent");
		page.put(0x42, "ConfigFrequency");
		page.put(0x43, "ConfigApparentPower");
		page.put(0x44, "ConfigActivePower");
		page.put(0x45, "ConfigPercentLoad");
		page.put(0x46, "ConfigTemperature");
		page.put(0x47, "ConfigHumidity");
		page.put(0x50, "SwitchOnControl");
		page.put(0x51, "SwitchOffControl");
		page.put(0x52, "ToggleControl");
		page.put(0x53, "LowVoltageTransfer");
		page.put(0x54, "HighVoltageTransfer");
		page.put(0x55, "DelayBeforeReboot");
		page.put(0x56, "DelayBeforeStartup");
		page.put(0x57, "DelayBeforeShutdown");
		page.put(0x58, "Test");
		page.put(0x59, "Vendorspecificcommand");
		page.put(0x60, "Present");
		page.put(0x61, "Good");
		page.put(0x62, "InternalFailure");
		page.put(0x63, "VoltageOutOfRange");
		page.put(0x64, "FrequencyOutOfRange");
		page.put(0x65, "Overload");
		page.put(0x66, "OverCharged");
		page.put(0x67, "OverTemperature");
		page.put(0x68, "ShutdownRequested");
		page.put(0x69, "ShutdownImminent");
		page.put(0x6A, "VendorSpecificAnswerValid");
		page.put(0x6B, "SwitchOn/Off");
		page.put(0x6C, "Switcheble");
		page.put(0x6D, "Used");
		page.put(0x6E, "Boost");
		page.put(0x6F, "Buck");
		page.put(0x70, "Initialized");
		page.put(0x71, "Tested");
		allPages.put(133, page = new HIDPage(133, "Battery System"));
		page.put(0x00, "Undefined");
		page.put(0x01, "SMBBatteryMode");
		page.put(0x02, "SMBBatteryStatus");
		page.put(0x03, "SMBAlarmWarning");
		page.put(0x04, "SMBChargerMode");
		page.put(0x05, "SMBChargerStatus");
		page.put(0x06, "SMBChargerSpecInfo");
		page.put(0x07, "SMBSelectorState");
		page.put(0x08, "SMBSelectorPreset");
		page.put(0x09, "SMBSelectorInfo");
		page.put(0x10, "OptionalMfgFunction1");
		page.put(0x11, "OptionalMfgFunction2");
		page.put(0x12, "OptionalMfgFunction3");
		page.put(0x13, "OptionalMfgFunction4");
		page.put(0x14, "OptionalMfgFunction5");
		page.put(0x15, "ConnectionToSMBus");
		page.put(0x16, "OutputConnection");
		page.put(0x17, "ChargerConnection");
		page.put(0x18, "BatteryInsertion");
		page.put(0x19, "Usenext");
		page.put(0x1A, "OKToUse");
		page.put(0x28, "ManufacturerAccess");
		page.put(0x29, "RemainingCapacityLimit");
		page.put(0x2A, "RemainingTimeLimit");
		page.put(0x2B, "AtRate");
		page.put(0x2C, "CapacityMode");
		page.put(0x2D, "BroadcastToCharger");
		page.put(0x2E, "PrimaryBattery");
		page.put(0x2F, "ChargeController");
		page.put(0x40, "TerminateCharge");
		page.put(0x41, "TermminateDischarge");
		page.put(0x42, "BelowRemainingCapacityLimit");
		page.put(0x43, "RemainingTimeLimitExpired");
		page.put(0x44, "Charging");
		page.put(0x45, "Discharging");
		page.put(0x46, "FullyCharged");
		page.put(0x47, "FullyDischarged");
		page.put(0x48, "ConditionningFlag");
		page.put(0x49, "AtRateOK");
		page.put(0x4A, "SMBErrorCode");
		page.put(0x4B, "NeedReplacement");
		page.put(0x60, "AtRateTimeToFull");
		page.put(0x61, "AtRateTimeToEmpty");
		page.put(0x62, "AverageCurrent");
		page.put(0x63, "Maxerror");
		page.put(0x64, "RelativeStateOfCharge");
		page.put(0x65, "AbsoluteStateOfCharge");
		page.put(0x66, "RemainingCapacity");
		page.put(0x67, "FullChargeCapacity");
		page.put(0x68, "RunTimeToEmpty");
		page.put(0x69, "AverageTimeToEmpty");
		page.put(0x6A, "AverageTimeToFull");
		page.put(0x6B, "CycleCount");
		page.put(0x80, "BattPackModelLevel");
		page.put(0x81, "InternalChargeController");
		page.put(0x82, "PrimaryBatterySupport");
		page.put(0x83, "DesignCapacity");
		page.put(0x84, "SpecificationInfo");
		page.put(0x85, "ManufacturerDate");
		page.put(0x86, "SerialNumber");
		page.put(0x87, "iManufacturerName");
		page.put(0x88, "iDevicename");
		page.put(0x89, "iDeviceChemistery");
		page.put(0x8A, "iManufacturerData");
		page.put(0x8B, "Rechargeable");
		page.put(0x8C, "WarningCapacityLimit");
		page.put(0x8D, "CapacityGranularity1");
		page.put(0x8E, "CapacityGranularity2");
		page.put(0xC0, "InhibitCharge");
		page.put(0xC1, "EnablePolling");
		page.put(0xC2, "ResetToZero");
		page.put(0xD0, "ACPresent");
		page.put(0xD1, "BatteryPresent");
		page.put(0xD2, "PowerFail");
		page.put(0xD3, "AlarmInhibited");
		page.put(0xD4, "ThermistorUnderRange");
		page.put(0xD5, "ThermistorHot");
		page.put(0xD6, "ThermistorCold");
		page.put(0xD7, "ThermistorOverRange");
		page.put(0xD8, "VoltageOutOfRange");
		page.put(0xD9, "CurrentOutOfRange");
		page.put(0xDA, "CurrentNotRegulated");
		page.put(0xDB, "VoltageNotRegulated");
		page.put(0xDC, "MasterMode");
		page.put(0xDD, "ChargerBattery/HostControlled");
		page.put(0xF0, "ChargerSpecInfo");
		page.put(0xF1, "ChargerSpecRef");
		page.put(0xF2, "Level2");
		page.put(0xF3, "Level3");
		allPages.put(140, page = new HIDPage(140, "Bar Code Scanner"));
		allPages.put(141, page = new HIDPage(141, "Scale Device"));
		allPages.put(144, page = new HIDPage(144, "Camera Control"));
		allPages.put(145, page = new HIDPage(145, "Arcade Device"));

		// # Some Micro$oft non-standard extensions

		allPages.put(0xff00, page = new HIDPage(0xff00, "Microsoft"));
		page.put(0xe9, "Base Up");
		page.put(0xea, "Base Down");

		// # APC non-standard page? (1.6.2003) Riccardo "VIC" Torrini
		allPages.put(0xff84, page = new HIDPage(0xff84, "__APC_Power Device"));
		page.put(0x00, "Undefined");
		page.put(0x01, "iName");
		page.put(0x02, "PresentStatus");
		page.put(0x03, "ChangedStatus");
		page.put(0x04, "UPS");
		page.put(0x05, "PowerSupply");
		page.put(0x10, "BatterySystem");
		page.put(0x11, "BatterySystemID");
		page.put(0x12, "Battery");
		page.put(0x13, "BatteryID");
		page.put(0x14, "Charger");
		page.put(0x15, "ChargerID");
		page.put(0x16, "PowerConverter");
		page.put(0x17, "PowerConverterID");
		page.put(0x18, "OutletSystem");
		page.put(0x19, "OutletSystemID");
		page.put(0x1A, "Input");
		page.put(0x1B, "InputID");
		page.put(0x1C, "Output");
		page.put(0x1D, "OutputID");
		page.put(0x1E, "Flow");
		page.put(0x1F, "FlowID");
		page.put(0x20, "Outlet");
		page.put(0x21, "OutletID");
		page.put(0x22, "Gang");
		page.put(0x23, "GangID");
		page.put(0x24, "Sink");
		page.put(0x25, "SinkID");
		page.put(0x30, "Voltage");
		page.put(0x31, "Current");
		page.put(0x32, "Frequency");
		page.put(0x33, "ApparentPower");
		page.put(0x34, "ActivePower");
		page.put(0x35, "PercentLoad");
		page.put(0x36, "Temperature");
		page.put(0x37, "Humidity");
		page.put(0x40, "ConfigVoltage");
		page.put(0x41, "ConfigCurrent");
		page.put(0x42, "ConfigFrequency");
		page.put(0x43, "ConfigApparentPower");
		page.put(0x44, "ConfigActivePower");
		page.put(0x45, "ConfigPercentLoad");
		page.put(0x46, "ConfigTemperature");
		page.put(0x47, "ConfigHumidity");
		page.put(0x50, "SwitchOnControl");
		page.put(0x51, "SwitchOffControl");
		page.put(0x52, "ToggleControl");
		page.put(0x53, "LowVoltageTransfer");
		page.put(0x54, "HighVoltageTransfer");
		page.put(0x55, "DelayBeforeReboot");
		page.put(0x56, "DelayBeforeStartup");
		page.put(0x57, "DelayBeforeShutdown");
		page.put(0x58, "Test");
		page.put(0x59, "Vendorspecificcommand");
		page.put(0x60, "Present");
		page.put(0x61, "Good");
		page.put(0x62, "InternalFailure");
		page.put(0x63, "VoltageOutOfRange");
		page.put(0x64, "FrequencyOutOfRange");
		page.put(0x65, "Overload");
		page.put(0x66, "OverCharged");
		page.put(0x67, "OverTemperature");
		page.put(0x68, "ShutdownRequested");
		page.put(0x69, "ShutdownImminent");
		page.put(0x6A, "VendorSpecificAnswerValid");
		page.put(0x6B, "SwitchOn/Off");
		page.put(0x6C, "Switcheble");
		page.put(0x6D, "Used");
		page.put(0x6E, "Boost");
		page.put(0x6F, "Buck");
		page.put(0x70, "Initialized");
		page.put(0x71, "Tested");

		allPages.put(0xff85, page = new HIDPage(0xff85, "__APC_Power Device"));
		page.put(0x00, "Undefined");
		page.put(0x01, "SMBBatteryMode");
		page.put(0x02, "SMBBatteryStatus");
		page.put(0x03, "SMBAlarmWarning");
		page.put(0x04, "SMBChargerMode");
		page.put(0x05, "SMBChargerStatus");
		page.put(0x06, "SMBChargerSpecInfo");
		page.put(0x07, "SMBSelectorState");
		page.put(0x08, "SMBSelectorPreset");
		page.put(0x09, "SMBSelectorInfo");
		page.put(0x10, "OptionalMfgFunction1");
		page.put(0x11, "OptionalMfgFunction2");
		page.put(0x12, "OptionalMfgFunction3");
		page.put(0x13, "OptionalMfgFunction4");
		page.put(0x14, "OptionalMfgFunction5");
		page.put(0x15, "ConnectionToSMBus");
		page.put(0x16, "OutputConnection");
		page.put(0x17, "ChargerConnection");
		page.put(0x18, "BatteryInsertion");
		page.put(0x19, "Usenext");
		page.put(0x1A, "OKToUse");
		page.put(0x28, "ManufacturerAccess");
		page.put(0x29, "RemainingCapacityLimit");
		page.put(0x2A, "RemainingTimeLimit");
		page.put(0x2B, "AtRate");
		page.put(0x2C, "CapacityMode");
		page.put(0x2D, "BroadcastToCharger");
		page.put(0x2E, "PrimaryBattery");
		page.put(0x2F, "ChargeController");
		page.put(0x40, "TerminateCharge");
		page.put(0x41, "TermminateDischarge");
		page.put(0x42, "BelowRemainingCapacityLimit");
		page.put(0x43, "RemainingTimeLimitExpired");
		page.put(0x44, "Charging");
		page.put(0x45, "Discharging");
		page.put(0x46, "FullyCharged");
		page.put(0x47, "FullyDischarged");
		page.put(0x48, "ConditionningFlag");
		page.put(0x49, "AtRateOK");
		page.put(0x4A, "SMBErrorCode");
		page.put(0x4B, "NeedReplacement");
		page.put(0x60, "AtRateTimeToFull");
		page.put(0x61, "AtRateTimeToEmpty");
		page.put(0x62, "AverageCurrent");
		page.put(0x63, "Maxerror");
		page.put(0x64, "RelativeStateOfCharge");
		page.put(0x65, "AbsoluteStateOfCharge");
		page.put(0x66, "RemainingCapacity");
		page.put(0x67, "FullChargeCapacity");
		page.put(0x68, "RunTimeToEmpty");
		page.put(0x69, "AverageTimeToEmpty");
		page.put(0x6A, "AverageTimeToFull");
		page.put(0x6B, "CycleCount");
		page.put(0x80, "BattPackModelLevel");
		page.put(0x81, "InternalChargeController");
		page.put(0x82, "PrimaryBatterySupport");
		page.put(0x83, "DesignCapacity");
		page.put(0x84, "SpecificationInfo");
		page.put(0x85, "ManufacturerDate");
		page.put(0x86, "SerialNumber");
		page.put(0x87, "iManufacturerName");
		page.put(0x88, "iDevicename");
		page.put(0x89, "iDeviceChemistery");
		page.put(0x8A, "iManufacturerData");
		page.put(0x8B, "Rechargeable");
		page.put(0x8C, "WarningCapacityLimit");
		page.put(0x8D, "CapacityGranularity1");
		page.put(0x8E, "CapacityGranularity2");
		page.put(0xC0, "InhibitCharge");
		page.put(0xC1, "EnablePolling");
		page.put(0xC2, "ResetToZero");
		page.put(0xD0, "ACPresent");
		page.put(0xD1, "BatteryPresent");
		page.put(0xD2, "PowerFail");
		page.put(0xD3, "AlarmInhibited");
		page.put(0xD4, "ThermistorUnderRange");
		page.put(0xD5, "ThermistorHot");
		page.put(0xD6, "ThermistorCold");
		page.put(0xD7, "ThermistorOverRange");
		page.put(0xD8, "VoltageOutOfRange");
		page.put(0xD9, "CurrentOutOfRange");
		page.put(0xDA, "CurrentNotRegulated");
		page.put(0xDB, "VoltageNotRegulated");
		page.put(0xDC, "MasterMode");
		page.put(0xDD, "ChargerBattery/HostControlled");
		page.put(0xF0, "ChargerSpecInfo");
		page.put(0xF1, "ChargerSpecRef");
		page.put(0xF2, "Level2");
		page.put(0xF3, "Level3	");
	}
	
	
	public static HIDPage getPage(int pageId){		
		return allPages.get(pageId); 
	}
	
	
}
